name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version you prefer
          registry-url: "https://registry.npmjs.org" # Ensure the registry URL is set

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if this is the first release
        id: check_version
        run: |
          if [ -z "$(git tag)" ]; then
            echo "first_release=true" >> $GITHUB_ENV
          else
            echo "first_release=false" >> $GITHUB_ENV
          fi

      - name: Get current version
        id: get_version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Bump version and push tag
        if: env.first_release == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          NEW_VERSION=$(npm version patch -m "chore(release): %s")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main --follow-tags

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
